spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group

spring.mail.host=ba4uuop7tqxn.mailtrap.ru
spring.mail.port=2525
spring.mail.username=ba4uuop7tqxn
spring.mail.password=bazbklqijgubk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

server.port=8081